name             'essentia'
maintainer       'Sean M. Sullivan'
maintainer_email 'sean@pulselocker.com'
license          'Apache 2.0'
description      'Installs/Configures Essentia audio library'
long_description 'Installs/Configures Essentia audio library'
version          '0.1.0'

depends 'build-essential'
depends 'apt'
depends 'python'
